### ISSUE TITLE
Links inside sortable elements can be sorted separately.

### ISSUE THREAD

**Issue by iwayanwirka** [rkusa/zepto-dnd#17]
Hello, I found one issue on my test. I put paragraph on every sortable element and one of the paragraph has a link. Sortable items are working very well, the problem is my link on the paragraph can be sorted separately from the paragraph itself. Here the test http://duststone.com/editor/zepto-dnd-test.html

I use FF 21.0.

Thanks anyway.

**Comment by rkusa** [comment]
Thanks for reporting! Could you please test these changes?

**Comment by iwayanwirka** [comment]
Hello rkusa,
Very cool, it works now.

Thank you!
