### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by CharlieHess** [rkusa/zepto-dnd#18]
The page [here](http://ma.rkusa.st/zepto-dnd/sortable.html) could use some lovin'. Particularly the events section threw me off. I'd like to know the item that moved, and its new index in the list. For some reason these are embedded within `_args`.
`item = e._args.item[0]`
`index = e._args.index`

As a side-note, when I swap two `sortable` items in a list, I get the same `li` for both `update` events, but two different indices: 1 and -1. Seems like a bug?

**Comment by rkusa** [comment]
Thanks for reporting your issue! You should get both `item` and `index` through the second argument of the event handler, e.g.:

```js
sortable.on('sortable:update', function (e, ui) {
  console.log(ui.item, ui.index)
})
```

If you are fine with getting the jQuery/Zepto object of the element `ui.item` is fine. `ui.item[0]` is for getting the plain DOM object.

**Comment by rkusa** [comment]
The double event should be fixed :-)
