### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by rkusa** [rkusa/zepto-dnd#19]
Refs rkusa/touch-dnd#4

**Comment by rkusa** [comment]
@janegbert Scrolling does work in Chrome. In FF not: https://bugzilla.mozilla.org/show_bug.cgi?id=41708

Maybe https://github.com/martindrapeau/jQueryDndPageScroll helps?

**Comment by janegbert** [comment]
Thanks, that does make the scrolling work better. Now I have to find a way to get the scroll wheel to work while dragging. Also the scrolling in `touch-dnd` is better in the way that when the mouse leaves the browser it keeps on scrolling the document.

**Comment by rchavik** [comment]
Somehow jquery.dnd.pagescroll didn't help for me.  Is there other solution/workaround?

I tried to create a patch by looking into [the way Sortable does it](https://github.com/RubaXa/Sortable/blob/c6a536aa3f999b2c556f301527fa1e7186a67d65/Sortable.js#L83) but can't figure it out.

**Comment by rchavik** [comment]
Hello,

I managed to get it to scroll somewhat using the following crude way:

```diff
diff --git a/zepto-dnd.js b/zepto-dnd.js
index 3546187..82adeb9 100644
--- a/zepto-dnd.js
+++ b/zepto-dnd.js
@@ -1,5 +1,20 @@
 !function($) {
   var nextId = 0
+
+  var autoscroll = function (e) {
+    var
+      h = window.innerHeight,
+      y = e.originalEvent.pageY - window.pageYOffset
+    if (y >= h - 40) {
+      console.log('scrolling near bottom');
+      window.scrollByLines(1);
+    }
+    if (y <= 40) {
+      console.log('scrolling near top');
+      window.scrollByLines(-1);
+    }
+  }
+
   var Dragging = function() {
     this.eventHandler = $('<div />')
     this.origin = this.el = null
@@ -235,6 +250,7 @@
     this.el
     .on('dragstart', $.proxy(this.start, this))
     .on('dragend',   $.proxy(this.end, this))
+    .on('dragover',   $.proxy(autoscroll, this))
     .prop('draggable', true)
 
     // Prevents dragging from starting on specified elements.
@@ -662,6 +678,8 @@
   Sortable.prototype.over = function(e) {
     if (!this.accept || this.opts.disabled) return
 
+    autoscroll(e);
+
     e.preventDefault() // allow drop
     e.stopPropagation()
```

I'm not sure where the autoscroll() should be defined as it needs to be called by both `Draggable` and `Sortable`. Is this a correct approach?

This also means that scrolling only works when we're moving an element that has `Draggable` or `Sortable` attached **over another** `Draggable`/`Sortable`.  

Also, we cannot move a `Draggable` to a `Sortable` that's not currently in the view port.

**Comment by rchavik** [comment]
> This also means that scrolling only works when we're moving an element that has Draggable or Sortable attached over another Draggable/Sortable. 

Found an 'workaround' by adding a `dragover` listener on `document` level as noted in https://bugzilla.mozilla.org/show_bug.cgi?id=505521#c8

**Comment by rchavik** [comment]
Okay. I have some modifications that include scrolling.

You can test the changes here: http://jsbin.com/witura/2.  There's a way off screen sortable on the bottom right of the viewport.  Drag an element and move it to the bottom right edge of the screen.

The changes include:

- Enable scrolling draggable/sortable in FF
- Enable text selection when handle is used
- Enable using clone of draggable/sortable element as placeholder
- Turn off/on dragImage
- Animation with CSS transition. Based on Rubaxa's. Has bugs.

Known problem:
- Instances are sometimes left in a disabled state (`this.opts.disabled == false`) causing things to fail.  I'm not sure what's causing this. I'm guessing maybe a race condition somewhere?
- Animation is not working properly. As you can see in the test page, one element is animated, while the other is not.
- Scrolling is not very smooth

Let me know if you want these as a PR.

**Comment by rkusa** [comment]
@rchavik Thanks for your work on this issue! A PR would be welcome. I could also have a look at the remaining problems.

**Comment by rchavik** [comment]
Great, I will test a bit more and submit them as a PR.

I just noticed some issue with the scroller; it's not working as expected in chrome, ie: chrome only triggers one `dragover` event. This causes the `Scroller.scroll` only called once. FF works fine since it triggers several `dragover` events on the body.
