### ISSUE TITLE
Droppables inside a sortable and using scope or accept

### ISSUE THREAD

**Issue by janegbert** [rkusa/zepto-dnd#20]
I'm trying to create a DND-interface for newsletter HTML. Users can drag containers into a `sortable` and drag blocks (of content) into those sortable containers. The sortable must only accept containers and the containers have droppables which must only accept blocks.

I created a sortable with nested droppables. I have set `scope: 'container'` for the sortable and `scope: 'block'` for the droppables. I expected the droppables to refuse a draggable set to `scope: 'container'`, but it seems to "pass security" because the enclosing sortable has already accepted it.

My workaround is to use `hasClass` in `droppable:receive` to check if the current draggable can be accepted.

Is this a bug or am I missing something in the documentation?

**Comment by rkusa** [comment]
Should be fixed, thanks for reporting!
