### ISSUE TITLE
Draggable to NON-connected sortable in iframe

### ISSUE THREAD

**Issue by asmaliukas** [rkusa/zepto-dnd#27]
If you remove `connectWith: $('#list', $("#sortable")[0].contentDocument)` line from this example:
http://ma.rkusa.st/zepto-dnd/example.html

The FIRST (and only first) element is still able to be dragged to sortable (even not connected one)..

Strange case..

Mac OS Chrome.

**Comment by rkusa** [comment]
Fixed in `1.3.1`. Thanks for reporting!
